name: property_management
description: نظام إدارة العقارات - تطبيق شامل لإدارة العقارات والمستأجرين
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & Navigation
  flutter_bloc: ^8.1.3
  go_router: ^14.2.0
  flutter_screenutil: ^5.9.0
  flutter_staggered_grid_view: ^0.7.0
  
  # State Management
  bloc: ^8.1.2
  equatable: ^2.0.5
  
  # Data & Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  
  # HTTP & API
  dio: ^5.3.2
  connectivity_plus: ^5.0.1
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.1.0
  logger: ^2.0.2+1
  
  # Forms & Validation
  formz: ^0.6.1
  
  # Charts & Analytics
  fl_chart: ^0.65.0
  
  # PDF & Export
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Icons
  cupertino_icons: ^1.0.6
  lucide_icons: ^0.294.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  generate: true
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
          
  assets:
    - assets/images/
    - assets/icons/