name: property_management
description: نظام إدارة العقارات - تطبيق شامل لإدارة العقارات والمستأجرين
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Navigation
  flutter_bloc: ^9.0.0
  go_router: ^14.0.0
  flutter_screenutil: ^6.0.0
  flutter_staggered_grid_view: ^0.8.0

  # State Management
  bloc: ^9.0.0
  equatable: ^3.0.0

  # Data & Storage
  sqflite: ^2.4.0
  path: ^1.9.0
  shared_preferences: ^3.0.0

  # HTTP & API
  dio: ^6.0.0
  connectivity_plus: ^6.0.0

  # Utils
  intl: ^0.21.0
  uuid: ^5.0.0
  logger: ^3.0.0

  # Forms & Validation
  formz: ^0.7.0

  # Charts & Analytics
  fl_chart: ^1.0.0

  # PDF & Export
  pdf: ^4.0.0
  printing: ^6.0.0

  # Icons
  cupertino_icons: ^1.0.2
  flutter_vector_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.26.2

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600

  assets:
    - assets/images/
    - assets/icons/
