flutter pub add [*]
flutter pub add test
flutter pub add material_color_utilities
flutter pub add meta
flutter pub add petitparser
flutter pub add vector_math
flutter pub add xml
flutter pub add leak_tracker
flutter pub add leak_tracker_flutter_testing
flutter pub add leak_tracker_testing
flutter pub add process
flutter pub add test_api
flutter pub add test_core
flutter pub add vm_service
