name: Build Flutter Windows EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build for Windows
        run: flutter build windows

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-windows-exe
          path: build/windows/runner/Release/
